package org.opendatakit.demoAndroidCommonClasses.views;

public enum ExecutorRequestType {
    UPDATE_EXECUTOR_CONTEXT,
    GET_ROLES_LIST,
    GET_USERS_LIST,
    GET_ALL_TABLE_IDS,
    ARBITRARY_QUERY,
    USER_TABLE_QUERY,
    USER_TABLE_GET_ROWS,
    USER_TABLE_GET_MOST_RECENT_ROW,
    USER_TABLE_UPDATE_ROW,
    USER_TABLE_CHANGE_ACCESS_FILTER_ROW,
    USER_TABLE_DELETE_ROW,
    USER_TABLE_ADD_ROW,
    USER_TABLE_ADD_CHECKPOINT,
    USER_TABLE_SAVE_CHECKPOINT_AS_INCOMPLETE,
    USER_TABLE_SAVE_CHECKPOINT_AS_COMPLETE,
    USER_TABLE_DELETE_ALL_CHECKPOINTS,
    USER_TABLE_DELETE_LAST_CHECKPOINT;

    private ExecutorRequestType() {
    }
}
